export const THERAPIST_LOGIN_REQUEST = "THERAPIST_LOGIN_REQUEST";
export const THERAPIST_LOGIN_SUCCESS = "THERAPIST_LOGIN_SUCCESS";
export const THERAPIST_LOGIN_FAIL = "THERAPIST_LOGIN_FAIL";
export const THERAPIST_LOGOUT = "THERAPIST_LOGOUT";

export const THERAPIST_UPDATE_PROFILE_REQUEST = "THERAPIST_UPDATE_PROFILE_REQUEST";
export const THERAPIST_UPDATE_PROFILE_SUCCESS = "THERAPIST_UPDATE_PROFILE_SUCCESS";
export const THERAPIST_UPDATE_PROFILE_FAIL = "THERAPIST_UPDATE_PROFILE_FAIL";

export const THERAPIST_LIST_REQUEST = "THERAPIST_LIST_REQUEST";
export const THERAPIST_LIST_SUCCESS = "THERAPIST_LIST_SUCCESS";
export const THERAPIST_LIST_FAIL = "THERAPIST_LIST_FAIL";

/*
export const THERAPIST_ = "aqui";
export const THERAPIST_ = "aqui";
export const THERAPIST_ = "aqui";

*/
